# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retainer',
            name='work_year',
            field=models.IntegerField(choices=[(13, 2013), (14, 2014), (15, 2015), (16, 2016), (17, 2017)], default=2017),
        ),
    ]
